services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  OrionIX_Quantum:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/OrionIX_Quantum/OrionIX_Quantum:${WEBUI_DOCKER_TAG-main}
    container_name: OrionIX Quantum
    volumes:
      - OrionIX_Quantum:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OrionIX_Quantum_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  OrionIX_Quantum: {}
