apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: OrionIX Quantum
  name: OrionIX Quantum-pvc
  namespace: OrionIX Quantum
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi